export const AUDIT_ACTION = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  UPDATE_STATUS: "UPDATE_STATUS",
  ASSIGN: "ASSIGN",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
} as const;

export const AUDIT_ENTITY = {
  POWER_SCHEDULE: "POWER_SCHEDULE",
  OUTAGE_REPORT: "OUTAGE_REPORT",
  POWER_SERVICE: "POWER_SERVICE",
  SERVICE_REQUEST: "SERVICE_REQUEST",
  PROVIDER_PROFILE: "PROVIDER_PROFILE",
  PAYMENT: "PAYMENT",
  USER: "USER",
} as const;

export type TAuditAction = (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];
export type TAuditEntity = (typeof AUDIT_ENTITY)[keyof typeof AUDIT_ENTITY];